[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
yaml-rust2 = "0.8.1"
log = "0.4.22"
either = "1.13.0"
scraper = "0.20.0"
ego-tree = "0.6.2"
regex = "1.10.6"
once_cell = "1.19.0"
lewp-css = "0.2.0"
markdown = "0.3.0"
