name: Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache builder build
        id: cache-builder
        uses: actions/cache@v4
        with:
          path: |
            builder/target/release/builder
          key: builder-${{ hashFiles('builder/Cargo.toml', 'builder/Cargo.lock', 'builder/**/*.rs') }}
      - name: Build builder
        if: steps.cache-builder.outputs.cache-hit != 'true'
        run: cd builder && cargo build --release && cd ..
      - run: builder/target/release/builder assemble
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'
      - id: deployment
        uses: actions/deploy-pages@v4
